export const districts = [
  { id: 'kottayam', name: 'Kottayam', hospitalCount: 12 },
  { id: 'idukki', name: 'Idukki', hospitalCount: 8 },
  { id: 'ernakulam', name: 'Ernakulam', hospitalCount: 18 },
  { id: 'thrissur', name: 'Thrissur', hospitalCount: 15 },
  { id: 'thiruvananthapuram', name: 'Thiruvananthapuram', hospitalCount: 20 },
]

export const departments = [
  { id: 'cardiology', name: 'Cardiology', icon: 'Heart' },
  { id: 'neurology', name: 'Neurology', icon: 'Brain' },
  { id: 'orthopedics', name: 'Orthopedics', icon: 'Bone' },
  { id: 'pediatrics', name: 'Pediatrics', icon: 'Baby' },
  { id: 'dermatology', name: 'Dermatology', icon: 'Scan' },
  { id: 'ophthalmology', name: 'Ophthalmology', icon: 'Eye' },
  { id: 'ent', name: 'ENT', icon: 'Ear' },
  { id: 'gynecology', name: 'Gynecology', icon: 'Users' },
  { id: 'general-medicine', name: 'General Medicine', icon: 'Stethoscope' },
  { id: 'dentistry', name: 'Dentistry', icon: 'Smile' },
]

export const hospitals = [
  {
    id: '1',
    name: 'Green Valley Medical Center',
    district: 'thiruvananthapuram',
    address: 'Anayara, Thiruvananthapuram',
    rating: 4.8,
    departments: ['cardiology', 'neurology', 'orthopedics', 'pediatrics', 'general-medicine'],
    beds: 500,
    established: 2002,
    image: '/hospitals/kims.jpg',
    featured: true,
  },
  {
    id: '2',
    name: 'Astra Medical Center',
    district: 'ernakulam',
    address: 'Cheranalloor, Kochi',
    rating: 4.9,
    departments: ['cardiology', 'neurology', 'orthopedics', 'pediatrics', 'gynecology'],
    beds: 670,
    established: 2014,
    image: '/hospitals/aster.jpg',
    featured: true,
  },
  {
    id: '3',
    name: 'Beacon Health Center',
    district: 'ernakulam',
    address: 'AIMS Ponekkara, Kochi',
    rating: 4.7,
    departments: ['cardiology', 'neurology', 'orthopedics', 'dermatology', 'ophthalmology'],
    beds: 450,
    established: 1998,
    image: '/hospitals/amrita.jpg',
    featured: true,
  },
  {
    id: '4',
    name: 'Willowbrook Hospital',
    district: 'kottayam',
    address: 'Thellakom, Kottayam',
    rating: 4.6,
    departments: ['cardiology', 'pediatrics', 'gynecology', 'general-medicine', 'dentistry'],
    beds: 350,
    established: 1978,
    image: '/hospitals/caritas.jpg',
    featured: false,
  },
  {
    id: '5',
    name: 'Summit Memorial Hospital',
    district: 'thrissur',
    address: 'East Fort, Thrissur',
    rating: 4.5,
    departments: ['cardiology', 'neurology', 'orthopedics', 'ent', 'general-medicine', 'dermatology'],
    beds: 400,
    established: 1951,
    image: '/hospitals/jubilee.jpg',
    featured: true,
  },
  {
    id: '6',
    name: 'Heritage Memorial Hospital',
    district: 'idukki',
    address: 'Painavu, Idukki',
    rating: 4.3,
    departments: ['general-medicine', 'pediatrics', 'gynecology', 'dentistry'],
    beds: 150,
    established: 1985,
    image: '/hospitals/tata.jpg',
    featured: false,
  },
]

export const doctors = [
  // Green Valley Medical Center doctors
  {
    id: '1',
    name: 'Dr. Arun Kumar',
    specialization: 'Cardiologist',
    department: 'cardiology',
    hospital: 'Green Valley Medical Center',
    hospitalId: '1',
    experience: 15,
    consultationFee: 800,
    rating: 4.9,
    availability: true,
    image: '/doctors/doctor1.jpg',
    education: 'MBBS, MD (Cardiology), DM',
    languages: ['English', 'Malayalam', 'Hindi'],
  },
  {
    id: '2',
    name: 'Dr. Neeraj Rao',
    specialization: 'Neurologist',
    department: 'neurology',
    hospital: 'Green Valley Medical Center',
    hospitalId: '1',
    experience: 14,
    consultationFee: 950,
    rating: 4.8,
    availability: true,
    image: '/doctors/doctor2.jpg',
    education: 'MBBS, MD (Neurology)',
    languages: ['English', 'Malayalam'],
  },
  {
    id: '3',
    name: 'Dr. Meera Nair',
    specialization: 'Orthopedic Surgeon',
    department: 'orthopedics',
    hospital: 'Green Valley Medical Center',
    hospitalId: '1',
    experience: 11,
    consultationFee: 900,
    rating: 4.7,
    availability: true,
    image: '/doctors/doctor3.jpg',
    education: 'MBBS, MS (Orthopedics)',
    languages: ['English', 'Malayalam', 'Tamil'],
  },
  {
    id: '4',
    name: 'Dr. Aisha Thomas',
    specialization: 'Pediatrician',
    department: 'pediatrics',
    hospital: 'Green Valley Medical Center',
    hospitalId: '1',
    experience: 10,
    consultationFee: 700,
    rating: 4.9,
    availability: true,
    image: '/doctors/doctor4.jpg',
    education: 'MBBS, MD (Pediatrics)',
    languages: ['English', 'Malayalam'],
  },
  {
    id: '5',
    name: 'Dr. Vivek Menon',
    specialization: 'General Physician',
    department: 'general-medicine',
    hospital: 'Green Valley Medical Center',
    hospitalId: '1',
    experience: 13,
    consultationFee: 650,
    rating: 4.8,
    availability: true,
    image: '/doctors/doctor5.jpg',
    education: 'MBBS, MD (General Medicine)',
    languages: ['English', 'Malayalam'],
  },

  // Astra Medical Center doctors
  {
    id: '6',
    name: 'Dr. Priya Menon',
    specialization: 'Neurologist',
    department: 'neurology',
    hospital: 'Astra Medical Center',
    hospitalId: '2',
    experience: 12,
    consultationFee: 1000,
    rating: 4.8,
    availability: true,
    image: '/doctors/doctor6.jpg',
    education: 'MBBS, MD (Neurology), DM',
    languages: ['English', 'Malayalam'],
  },
  {
    id: '7',
    name: 'Dr. Priyanka Das',
    specialization: 'Cardiologist',
    department: 'cardiology',
    hospital: 'Astra Medical Center',
    hospitalId: '2',
    experience: 13,
    consultationFee: 820,
    rating: 4.7,
    availability: true,
    image: '/doctors/doctor7.jpg',
    education: 'MBBS, MD (Cardiology), DM',
    languages: ['English', 'Malayalam'],
  },
  {
    id: '8',
    name: 'Dr. Rohan Verma',
    specialization: 'Orthopedic Surgeon',
    department: 'orthopedics',
    hospital: 'Astra Medical Center',
    hospitalId: '2',
    experience: 9,
    consultationFee: 920,
    rating: 4.6,
    availability: true,
    image: '/doctors/doctor8.jpg',
    education: 'MBBS, MS (Orthopedics)',
    languages: ['English', 'Hindi'],
  },
  {
    id: '9',
    name: 'Dr. Sahana Joseph',
    specialization: 'Pediatrician',
    department: 'pediatrics',
    hospital: 'Astra Medical Center',
    hospitalId: '2',
    experience: 8,
    consultationFee: 680,
    rating: 4.8,
    availability: true,
    image: '/doctors/doctor9.jpg',
    education: 'MBBS, MD (Pediatrics)',
    languages: ['English', 'Malayalam'],
  },
  {
    id: '10',
    name: 'Dr. Anitha Varma',
    specialization: 'Gynecologist',
    department: 'gynecology',
    hospital: 'Astra Medical Center',
    hospitalId: '2',
    experience: 18,
    consultationFee: 850,
    rating: 4.8,
    availability: true,
    image: '/doctors/doctor10.jpg',
    education: 'MBBS, MD (OBG), DGO',
    languages: ['English', 'Malayalam'],
  },

  // Beacon Health Center doctors
  {
    id: '11',
    name: 'Dr. Sanjay Gupta',
    specialization: 'Cardiologist',
    department: 'cardiology',
    hospital: 'Beacon Health Center',
    hospitalId: '3',
    experience: 17,
    consultationFee: 880,
    rating: 4.9,
    availability: true,
    image: '/doctors/doctor11.jpg',
    education: 'MBBS, MD (Cardiology), DM',
    languages: ['English', 'Hindi'],
  },
  {
    id: '12',
    name: 'Dr. Meenakshi Iyer',
    specialization: 'Neurologist',
    department: 'neurology',
    hospital: 'Beacon Health Center',
    hospitalId: '3',
    experience: 12,
    consultationFee: 980,
    rating: 4.7,
    availability: true,
    image: '/doctors/doctor12.jpg',
    education: 'MBBS, MD (Neurology), DM',
    languages: ['English', 'Malayalam'],
  },
  {
    id: '13',
    name: 'Dr. Rajesh Nair',
    specialization: 'Orthopedic Surgeon',
    department: 'orthopedics',
    hospital: 'Beacon Health Center',
    hospitalId: '3',
    experience: 20,
    consultationFee: 900,
    rating: 4.7,
    availability: false,
    image: '/doctors/doctor13.jpg',
    education: 'MBBS, MS (Ortho), MCh',
    languages: ['English', 'Malayalam', 'Tamil'],
  },
  {
    id: '14',
    name: 'Dr. Kavya Menon',
    specialization: 'Dermatologist',
    department: 'dermatology',
    hospital: 'Beacon Health Center',
    hospitalId: '3',
    experience: 9,
    consultationFee: 720,
    rating: 4.6,
    availability: true,
    image: '/doctors/doctor14.jpg',
    education: 'MBBS, MD (Dermatology)',
    languages: ['English', 'Malayalam'],
  },
  {
    id: '15',
    name: 'Dr. Riya Sharma',
    specialization: 'Ophthalmologist',
    department: 'ophthalmology',
    hospital: 'Beacon Health Center',
    hospitalId: '3',
    experience: 11,
    consultationFee: 760,
    rating: 4.8,
    availability: true,
    image: '/doctors/doctor15.jpg',
    education: 'MBBS, MS (Ophthalmology)',
    languages: ['English', 'Hindi'],
  },

  // Willowbrook Hospital doctors
  {
    id: '16',
    name: 'Dr. Thomas Jose',
    specialization: 'Cardiologist',
    department: 'cardiology',
    hospital: 'Willowbrook Hospital',
    hospitalId: '4',
    experience: 18,
    consultationFee: 820,
    rating: 4.7,
    availability: true,
    image: '/doctors/doctor16.jpg',
    education: 'MBBS, MD (Cardiology)',
    languages: ['English', 'Malayalam'],
  },
  {
    id: '17',
    name: 'Dr. Lakshmi Devi',
    specialization: 'Pediatrician',
    department: 'pediatrics',
    hospital: 'Willowbrook Hospital',
    hospitalId: '4',
    experience: 10,
    consultationFee: 600,
    rating: 4.9,
    availability: true,
    image: '/doctors/doctor17.jpg',
    education: 'MBBS, MD (Pediatrics)',
    languages: ['English', 'Malayalam'],
  },
  {
    id: '18',
    name: 'Dr. Maya Mathew',
    specialization: 'Gynecologist',
    department: 'gynecology',
    hospital: 'Willowbrook Hospital',
    hospitalId: '4',
    experience: 13,
    consultationFee: 800,
    rating: 4.8,
    availability: true,
    image: '/doctors/doctor18.jpg',
    education: 'MBBS, MD (OBG), DGO',
    languages: ['English', 'Malayalam'],
  },
  {
    id: '19',
    name: 'Dr. Anup Krishnan',
    specialization: 'General Physician',
    department: 'general-medicine',
    hospital: 'Willowbrook Hospital',
    hospitalId: '4',
    experience: 15,
    consultationFee: 680,
    rating: 4.7,
    availability: true,
    image: '/doctors/doctor19.jpg',
    education: 'MBBS, MD (General Medicine)',
    languages: ['English', 'Malayalam'],
  },
  {
    id: '20',
    name: 'Dr. Anita George',
    specialization: 'Dentist',
    department: 'dentistry',
    hospital: 'Willowbrook Hospital',
    hospitalId: '4',
    experience: 12,
    consultationFee: 700,
    rating: 4.6,
    availability: true,
    image: '/doctors/doctor20.jpg',
    education: 'BDS, MDS (Conservative Dentistry)',
    languages: ['English', 'Malayalam'],
  },

  // Summit Memorial Hospital doctors
  {
    id: '21',
    name: 'Dr. Adeeb Khan',
    specialization: 'Cardiologist',
    department: 'cardiology',
    hospital: 'Summit Memorial Hospital',
    hospitalId: '5',
    experience: 16,
    consultationFee: 860,
    rating: 4.8,
    availability: true,
    image: '/doctors/doctor21.jpg',
    education: 'MBBS, MD (Cardiology), DM',
    languages: ['English', 'Hindi'],
  },
  {
    id: '22',
    name: 'Dr. Priya Suresh',
    specialization: 'Neurologist',
    department: 'neurology',
    hospital: 'Summit Memorial Hospital',
    hospitalId: '5',
    experience: 11,
    consultationFee: 960,
    rating: 4.7,
    availability: true,
    image: '/doctors/doctor22.jpg',
    education: 'MBBS, MD (Neurology), DM',
    languages: ['English', 'Malayalam'],
  },
  {
    id: '23',
    name: 'Dr. Kiran Menon',
    specialization: 'Orthopedic Surgeon',
    department: 'orthopedics',
    hospital: 'Summit Memorial Hospital',
    hospitalId: '5',
    experience: 10,
    consultationFee: 930,
    rating: 4.6,
    availability: true,
    image: '/doctors/doctor23.jpg',
    education: 'MBBS, MS (Orthopedics)',
    languages: ['English', 'Malayalam'],
  },
  {
    id: '24',
    name: 'Dr. Shweta Nair',
    specialization: 'ENT Specialist',
    department: 'ent',
    hospital: 'Summit Memorial Hospital',
    hospitalId: '5',
    experience: 9,
    consultationFee: 750,
    rating: 4.7,
    availability: true,
    image: '/doctors/doctor24.jpg',
    education: 'MBBS, MS (ENT)',
    languages: ['English', 'Malayalam'],
  },
  {
    id: '25',
    name: 'Dr. Amit Balan',
    specialization: 'General Physician',
    department: 'general-medicine',
    hospital: 'Summit Memorial Hospital',
    hospitalId: '5',
    experience: 14,
    consultationFee: 700,
    rating: 4.8,
    availability: true,
    image: '/doctors/doctor25.jpg',
    education: 'MBBS, MD (General Medicine)',
    languages: ['English', 'Malayalam'],
  },
  {
    id: '26',
    name: 'Dr. Suresh Pillai',
    specialization: 'Dermatologist',
    department: 'dermatology',
    hospital: 'Summit Memorial Hospital',
    hospitalId: '5',
    experience: 8,
    consultationFee: 700,
    rating: 4.6,
    availability: true,
    image: '/doctors/doctor26.jpg',
    education: 'MBBS, MD (Dermatology)',
    languages: ['English', 'Malayalam', 'Hindi'],
  },

  // Heritage Memorial Hospital doctors
  {
    id: '27',
    name: 'Dr. Nisha Raj',
    specialization: 'General Physician',
    department: 'general-medicine',
    hospital: 'Heritage Memorial Hospital',
    hospitalId: '6',
    experience: 12,
    consultationFee: 650,
    rating: 4.7,
    availability: true,
    image: '/doctors/doctor27.jpg',
    education: 'MBBS, MD (General Medicine)',
    languages: ['English', 'Malayalam', 'Hindi'],
  },
  {
    id: '28',
    name: 'Dr. Neha Varma',
    specialization: 'Pediatrician',
    department: 'pediatrics',
    hospital: 'Heritage Memorial Hospital',
    hospitalId: '6',
    experience: 9,
    consultationFee: 620,
    rating: 4.8,
    availability: true,
    image: '/doctors/doctor28.jpg',
    education: 'MBBS, MD (Pediatrics)',
    languages: ['English', 'Malayalam'],
  },
  {
    id: '29',
    name: 'Dr. Shilpa Nair',
    specialization: 'Gynecologist',
    department: 'gynecology',
    hospital: 'Heritage Memorial Hospital',
    hospitalId: '6',
    experience: 11,
    consultationFee: 780,
    rating: 4.6,
    availability: true,
    image: '/doctors/doctor29.jpg',
    education: 'MBBS, MD (OBG), DGO',
    languages: ['English', 'Malayalam'],
  },
  {
    id: '30',
    name: 'Dr. George Thomas',
    specialization: 'Dentist',
    department: 'dentistry',
    hospital: 'Heritage Memorial Hospital',
    hospitalId: '6',
    experience: 13,
    consultationFee: 700,
    rating: 4.7,
    availability: true,
    image: '/doctors/doctor30.jpg',
    education: 'BDS, MDS (Prosthodontics)',
    languages: ['English', 'Malayalam'],
  },
]

export interface Slot {
  id: string;
  startTime: string;
  endTime: string;
  maxPatients: number;
  currentBookings: number;
}

export const slots: Slot[] = [
  { id: 's1', startTime: '09:00 AM', endTime: '10:00 AM', maxPatients: 20, currentBookings: 20 },
  { id: 's2', startTime: '10:00 AM', endTime: '11:00 AM', maxPatients: 20, currentBookings: 18 },
  { id: 's3', startTime: '11:00 AM', endTime: '12:00 PM', maxPatients: 20, currentBookings: 5 },
  { id: 's4', startTime: '12:00 PM', endTime: '01:00 PM', maxPatients: 20, currentBookings: 12 },
  { id: 's5', startTime: '02:00 PM', endTime: '03:00 PM', maxPatients: 20, currentBookings: 8 },
  { id: 's6', startTime: '03:00 PM', endTime: '04:00 PM', maxPatients: 20, currentBookings: 19 },
  { id: 's7', startTime: '04:00 PM', endTime: '05:00 PM', maxPatients: 20, currentBookings: 20 },
  { id: 's8', startTime: '05:00 PM', endTime: '06:00 PM', maxPatients: 20, currentBookings: 2 },
];

export const mockAppointments = [
  {
    id: '1',
    patientName: 'John Doe',
    patientId: 'P001',
    doctorName: 'Dr. Arun Kumar',
    doctorId: '1',
    hospital: 'Green Valley Medical Center',
    department: 'Cardiology',
    date: '2026-05-15',
    time: '10:00 AM',
    status: 'confirmed',
    type: 'consultation',
    tokenNumber: 5,
    slot: { id: 's2', startTime: '10:00 AM', endTime: '11:00 AM', maxPatients: 20, currentBookings: 18 },
  },
  {
    id: '2',
    patientName: 'Jane Smith',
    patientId: 'P002',
    doctorName: 'Dr. Priya Menon',
    doctorId: '2',
    hospital: 'Astra Medical Center',
    department: 'Neurology',
    date: '2026-05-16',
    time: '02:00 PM',
    status: 'pending',
    type: 'follow-up',
    tokenNumber: 8,
    slot: { id: 's5', startTime: '02:00 PM', endTime: '03:00 PM', maxPatients: 20, currentBookings: 8 },
  },
  {
    id: '3',
    patientName: 'Mike Johnson',
    patientId: 'P003',
    doctorName: 'Dr. Lakshmi Devi',
    doctorId: '4',
    hospital: 'Willowbrook Hospital',
    department: 'Pediatrics',
    date: '2026-05-14',
    time: '11:00 AM',
    status: 'completed',
    type: 'consultation',
    tokenNumber: 2,
    slot: { id: 's3', startTime: '11:00 AM', endTime: '12:00 PM', maxPatients: 20, currentBookings: 5 },
  },
]

export const statistics = {
  totalHospitals: 73,
  totalDoctors: 450,
  totalPatients: 125000,
  appointmentsToday: 892,
  districts: 5,
  successRate: 98.5,
}



